// expect-exit: 52
// expect-stdout: 45
// while from the prelude: the rule becomes `loop { if (!c) break; b }`.
// break and continue inside the body remain the core's own — continue
// goes back to the top of the loop, which is where the condition is re-evaluated.
#include "../lib/sys.mc"
#include "../lib/prelude.mc"

i64 main() {
    i64 i = 0;
    i64 s = 0;
    while (i < 10) {
        s = s + i;
        i = i + 1;
    }
    putnum(s);                        // 0+1+...+9 = 45

    i64 j = 0;
    i64 t = 0;
    while (j < 100) {
        j = j + 1;
        if (j > 10) break;            // break exits the loop generated by the rule
        if (j == 3) continue;         // continue re-evaluates the condition: skips the 3
        t = t + j;
    }
    return t;                         // 55 - 3 = 52
}
