// syntax_demo_test.mc — the program that only the taught compiler compiles.
// It uses everything lib/user_syntax_demo.mc teaches: the M12 three (`enum`,
// `unless`, `bool`) and the M21 six (`bits`, `pipe`, `.+`, `~>`, `tmpl`,
// `make`), plus a `#infix` in the same file to show that a taught operator and
// a template operator live in ONE precedence order.
// With the default compiler (build/mc1) it fails right at the first useful
// line, with `type expected at top level` — `enum` there is just an identifier.
// expect-exit: 42
// lex-skip: it USES the taught `.+` operator; `.` is a lexeme in src/lex.mc since M44 and not in the frozen stage0 lexer, and --dump-tokens processes no directive

enum Color { GREEN, YELLOW, RED }

#token "<+>"
#infix "<+>" 9 left ($1 + $2) * 2            // Tier 1, next to the taught `.+`

// The body is recorded, never parsed here. Three things it has to survive:
//   T cells[N]   the substituted N is a TOKEN, so it folds in parse_dim
//   T_tag        one identifier: substitution is by whole lexeme, not by text
//   "T is T"     a string: the lexer never offers it for substitution
tmpl slot<T, N> {
    T cells[N];
    i64 T_tag = N;
    uptr kind = "T is T";
    st8(cells, 0);
    return T_tag + bits T / 8 + ld8(cells) + ld8(kind) - 'T';
}

make slot<i64, 3>;                           // -> i64 slot__i64__3()  = 3 + 8
make slot<u8, 2>;                            // -> i64 slot__u8__2()   = 2 + 1
make slot<i64, sum<1, 2>>;                   // `>>` split; memoized, generates nothing

i64 dbl(i64 x) { return x * 2; }
i64 inc(i64 x) { return x + 1; }

u64 box[4];                                  // two header words + two elements

// `bool` is an alias of u8: valid as a parameter type and a local type
i64 two(bool b) {
    unless (b == 0) {
        return 2;
    }
    return 0;
}

i64 main() {
    i64 n = GREEN;                           // 0, constant generated by the enum
    bool ok = 1;
    n = n + two(ok);                         // 2
    Color c = YELLOW;                        // `Color` became an alias of i64
    unless (c != YELLOW) {
        n = n + 10;                          // 12
    }

    uptr p = box;
    p ~> len = 3;                            // st64(p + 0, 3) — the handler read the `=`
    p ~> cap = 4;
    st64(p + 16, 7);                         // element 0
    n = n + p ~> len + p ~> cap + p ~> at(0);   // 12 + 3 + 4 + 7 = 26

    n = n + (50 .+ 60) - 100;                // saturates at 100: still 26
    n = n + (1 <+> 2) - 6;                   // Tier 1 in the same table: still 26
    n = n + pipe(2, dbl, inc);               // inc(dbl(2)) = 5 -> 31
    n = n + slot__i64__3() - 11;             // 3 + 8 = 11 -> 31
    n = n + slot__u8__2();                   // 2 + 1 = 3  -> 34
    return n + bits u32 / 4;                 // 32 / 4 = 8 -> 42
}
