// syntax_demo_test.mc — the program that only the M12-taught compiler compiles.
// Uses the three things from lib/user_syntax_demo.mc: `enum`, `unless` and `bool`.
// With the default compiler (build/mc1) it fails right at the first useful
// line, with `type expected at top level` — `enum` there is just an identifier.
// expect-exit: 42

enum Color { GREEN, YELLOW, RED }

// `bool` is an alias of u8: valid as a parameter type and a local type
i64 two(bool b) {
    unless (b == 0) {
        return 2;
    }
    return 0;
}

i64 main() {
    i64 n = GREEN;                 // 0, constant generated by the enum
    bool ok = 1;
    n = n + two(ok);              // 2
    Color c = YELLOW;               // `Color` became an alias of i64
    unless (c != YELLOW) {
        n = n + 40;
    }
    return n + RED * 0;       // 42
}
