#!/bin/sh
# check-shim.sh [MC] — M43 acceptance 1: the raw system-call shim is right
# BEFORE anything uses it (the M39/M42 probe discipline, docs/specs/M43.md
# § Architect's additions (a)).
#
# The probe is GENERATED here rather than checked in under tests/: the spec's
# file list names six isolation programs in tests/sandbox/ and this is not one
# of them, and tests/*.mc is untouchable for this milestone (acceptance 12).
#
# It proves four things about `sys6` (src/sysno_linux_aarch64.mc,
# src/sysno_linux_x86_64.mc), through the same one-line wrapper the host layer
# publishes as host_syscall6:
#
#   1. the NUMBER reaches the kernel        getpid through the shim == getpid
#                                           from the libc this binary links
#   2. a failure comes back as -errno       openat of a missing path == -2
#   3. arguments 1..3 reach the kernel      write(1, buf, n) through the shim
#   4. arguments 4..6 reach the kernel      mmap(0, 4096, PROT_READ, MAP_PRIVATE,
#                                           fd, 4096) of a file whose byte at
#                                           offset 4096 is known -- the sixth
#                                           kernel argument is the SEVENTH
#                                           parameter of sys6, which is x6 on
#                                           AArch64 and [rbp+16] on x86-64, the
#                                           one place the two shims differ in
#                                           kind rather than in numbers
#
# This must run ON a Linux host: it executes the probe. From macOS, run it
# inside Lima (`limactl shell mc-k7`) or on a Linux box with a cross-built
# compiler; see docs/reference/sandbox.md.
set -e
mc="${1:-build/mc1}"

if [ ! -x "$mc" ]; then
    echo "FAIL: compiler '$mc' not found or not executable"
    exit 1
fi

case "$(uname -s)" in
    Linux) ;;
    *) echo "check-shim: SKIPPED (this host is $(uname -s); the shim is Linux only)"; exit 0 ;;
esac

case "$(uname -m)" in
    aarch64|arm64) sysno=mc/sysno_linux_aarch64; musl=/lib/ld-musl-aarch64.so.1 ;;
    x86_64|amd64)  sysno=mc/sysno_linux_x86_64;  musl=/lib/ld-musl-x86_64.so.1 ;;
    *) echo "FAIL: unsupported machine $(uname -m)"; exit 1 ;;
esac

# `mc --exe` writes a musl interpreter path by default and takes --libc=gnu for
# the other family (post-M42). The probe has to RUN here, so the family is the
# one this host actually has on disk -- the same question
# scripts/test-exe.sh asks.
libcflag=
[ -e "$musl" ] || libcflag=--libc=gnu

out=build/shim
rm -rf "$out"; mkdir -p "$out"

# 8192 zero bytes with 'M' at offset 4096 -- the target of the six-argument mmap
dd if=/dev/zero of="$out/data.bin" bs=4096 count=2 2>/dev/null
printf 'M' | dd of="$out/data.bin" bs=1 seek=4096 conv=notrunc 2>/dev/null
data=$(pwd)/$out/data.bin

cat > "$out/probe.mc" <<EOF
// probe.mc — generated by scripts/check-shim.sh (M43 acceptance 1).
#include <$sysno>

// The libc this binary links, for the comparison the acceptance asks for.
extern i64 getpid();
extern i64 write(i64 fd, uptr buf, i64 n);

// src/host_linux.mc's host_syscall6, verbatim: what is measured here is the
// host-layer entry point the sandbox calls, not sys6 behind its back.
i64 host_syscall6(i64 n, i64 a, i64 b, i64 c, i64 d, i64 e, i64 f) {
    return sys6(n, a, b, c, d, e, f);
}

i64 sc(i64 sn, i64 a, i64 b, i64 c, i64 d, i64 e, i64 f) {
    return host_syscall6(host_sysno(sn), a, b, c, d, e, f);
}

#define AT_FDCWD    -100
#define O_RDONLY       0
#define PROT_READ      1
#define MAP_PRIVATE    2

u8 nbuf[32];
i64 fails = 0;

i64 slen(uptr s) {
    i64 n = 0;
    loop { if (ld8(s + n) == 0) break; n = n + 1; }
    return n;
}

void puts0(uptr s) { write(1, s, slen(s)); }

void pnum(i64 v) {
    if (v < 0) { puts0("-"); v = 0 - v; }
    i64 i = 24;
    loop {
        i = i - 1;
        st8(nbuf + i, '0' + v % 10);
        v = v / 10;
        if (v == 0) break;
    }
    write(1, nbuf + i, 24 - i);
}

void say(uptr label, i64 got, i64 want, i64 eq) {
    puts0(label);
    puts0(" got "); pnum(got);
    puts0(" want "); pnum(want);
    if (eq) puts0("  ok\n");
    else  { puts0("  FAIL\n"); fails = fails + 1; }
}

i64 main() {
    // 1. the number reaches the kernel
    i64 a = sc(SN_GETPID, 0, 0, 0, 0, 0, 0);
    i64 b = getpid();
    say("getpid via the shim", a, b, a == b && a > 0);

    // 2. a failure comes back as -errno
    i64 r = sc(SN_OPENAT, AT_FDCWD, "/nonexistent", O_RDONLY, 0, 0, 0);
    say("openat /nonexistent", r, 0 - 2, r == 0 - 2);

    // 3. arguments 1..3
    uptr msg = "write(1, ...) through the shim reached fd 1\n";
    i64 w = sc(SN_WRITE, 1, msg, slen(msg), 0, 0, 0);
    say("write through the shim", w, slen(msg), w == slen(msg));

    // 4. arguments 4..6: the sixth kernel argument is sys6's seventh parameter
    i64 fd = sc(SN_OPENAT, AT_FDCWD, "$data", O_RDONLY, 0, 0, 0);
    if (fd < 0) { say("openat the data file", fd, 0, 0); return fails != 0; }
    i64 p = sc(SN_MMAP, 0, 4096, PROT_READ, MAP_PRIVATE, fd, 4096);
    if (p < 0 && p > 0 - 4096) { say("mmap at offset 4096", p, 0, 0); return fails != 0; }
    say("mmap at offset 4096, byte 0", ld8(p), 'M', ld8(p) == 'M');
    sc(SN_MUNMAP, p, 4096, 0, 0, 0, 0);
    sc(SN_CLOSE, fd, 0, 0, 0, 0, 0);

    if (fails) { puts0("check-shim: FAILURES\n"); return 1; }
    puts0("check-shim: the shim is right on $(uname -m)\n");
    return 0;
}
EOF

rm -f "$out/probe"
echo "check-shim: $mc --exe $libcflag $out/probe.mc"
"$mc" --exe $libcflag "$out/probe.mc" -o "$out/probe"
"$out/probe"
