// sandbox_profiles.mc — GENERATED by scripts/sandbox-trace.sh. Do not edit.
//
// The seccomp profiles of M43 step C (docs/specs/M43.md § 4,
// docs/reference/sandbox.md § The filter): the system calls a step is allowed
// to make without the supervisor being asked. Everything else reaches P as a
// SECCOMP_RET_USER_NOTIF notification, which is what turns a kill into a
// sentence -- `refused: syscall 198 (socket)`.
//
// They are MEASURED, never written: `strace -f` over every tests/*.mc compiled
// and run, and over `mc build examples/lang`, on each architecture and each C
// library. The recorded traces are tools/sandbox/*.list and this file is what
// the script printed from them; `sh scripts/sandbox-trace.sh --check` re-traces
// the host it runs on and fails if the trace and the list disagree in EITHER
// direction, or if regenerating this file from the lists does not reproduce it
// byte for byte.
//
// Three tables per architecture, plus one shared delta:
//
//   sbp_compile_*   the compile step: /mc itself, and the compiler it teaches
//   sbp_program_*   the run step: what an mc program plus its loader issues
//   sbp_gnu_*_*     what glibc's ld.so and libc need that musl's do not, per
//                   step -- the two are NOT the same list
//   sbp_threads     what --allow=threads adds (clone is not here: the filter
//                   gives it a flag test of its own, src/seccomp.mc)
//
// Each list is terminated by -1. An entry this architecture does not have
// answers -1 from host_sysno() and is skipped when the filter is built.

i64 sbp_compile_aarch64[] = {
    SN_BRK,
    SN_CLONE,
    SN_CLOSE,
    SN_EXECVE,
    SN_EXIT_GROUP,
    SN_FCHMODAT,
    SN_FCNTL,
    SN_MKDIRAT,
    SN_MMAP,
    SN_MPROTECT,
    SN_OPENAT,
    SN_PIPE2,
    SN_READ,
    SN_RT_SIGPROCMASK,
    SN_SET_TID_ADDRESS,
    SN_UNLINKAT,
    SN_WAIT4,
    SN_WRITE,
    -1
};

i64 sbp_gnu_compile_aarch64[] = {
    SN_CLONE3,
    SN_FACCESSAT,
    SN_FSTAT,
    SN_GETRANDOM,
    SN_MUNMAP,
    SN_PRLIMIT64,
    SN_RSEQ,
    SN_SET_ROBUST_LIST,
    -1
};

i64 sbp_program_aarch64[] = {
    SN_BRK,
    SN_CLOSE,
    SN_EXECVE,
    SN_EXIT_GROUP,
    SN_FCNTL,
    SN_GETDENTS64,
    SN_LSEEK,
    SN_MMAP,
    SN_MPROTECT,
    SN_MREMAP,
    SN_MUNMAP,
    SN_OPENAT,
    SN_READV,
    SN_RT_SIGPROCMASK,
    SN_SET_TID_ADDRESS,
    SN_WRITE,
    -1
};

i64 sbp_gnu_program_aarch64[] = {
    SN_FACCESSAT,
    SN_FSTAT,
    SN_GETRANDOM,
    SN_MADVISE,
    SN_PRLIMIT64,
    SN_READ,
    SN_RSEQ,
    SN_SET_ROBUST_LIST,
    -1
};

i64 sbp_compile_x86_64[] = {
    SN_ARCH_PRCTL,
    SN_BRK,
    SN_CHMOD,
    SN_CLONE,
    SN_CLOSE,
    SN_EXECVE,
    SN_EXIT_GROUP,
    SN_FCNTL,
    SN_MKDIR,
    SN_MMAP,
    SN_MPROTECT,
    SN_OPEN,
    SN_PIPE2,
    SN_READ,
    SN_RT_SIGPROCMASK,
    SN_SET_TID_ADDRESS,
    SN_UNLINK,
    SN_WAIT4,
    SN_WRITE,
    -1
};

i64 sbp_gnu_compile_x86_64[] = {
    SN_ACCESS,
    SN_CLONE3,
    SN_CREAT,
    SN_FSTAT,
    SN_GETRANDOM,
    SN_MUNMAP,
    SN_OPENAT,
    SN_PREAD64,
    SN_PRLIMIT64,
    SN_RSEQ,
    SN_SET_ROBUST_LIST,
    -1
};

i64 sbp_program_x86_64[] = {
    SN_ARCH_PRCTL,
    SN_BRK,
    SN_CLOSE,
    SN_EXECVE,
    SN_EXIT_GROUP,
    SN_FCNTL,
    SN_GETDENTS64,
    SN_LSEEK,
    SN_MMAP,
    SN_MPROTECT,
    SN_MREMAP,
    SN_MUNMAP,
    SN_OPEN,
    SN_READV,
    SN_RT_SIGPROCMASK,
    SN_SET_TID_ADDRESS,
    SN_WRITE,
    -1
};

i64 sbp_gnu_program_x86_64[] = {
    SN_ACCESS,
    SN_FSTAT,
    SN_GETRANDOM,
    SN_OPENAT,
    SN_PREAD64,
    SN_PRLIMIT64,
    SN_READ,
    SN_RSEQ,
    SN_SET_ROBUST_LIST,
    -1
};

i64 sbp_threads[] = {
    SN_CLOCK_NANOSLEEP,
    SN_EXIT,
    SN_FUTEX,
    SN_MADVISE,
    SN_MEMBARRIER,
    SN_NANOSLEEP,
    SN_RT_SIGACTION,
    -1
};

// the table for this architecture, by kind. host_arch() is the running
// machine, which is the only one whose numbers mean anything here.
uptr sbp_compile() {
    if (str_eq(host_arch(), "x86_64")) return sbp_compile_x86_64;
    return sbp_compile_aarch64;
}

uptr sbp_program() {
    if (str_eq(host_arch(), "x86_64")) return sbp_program_x86_64;
    return sbp_program_aarch64;
}

uptr sbp_gnu_compile() {
    if (str_eq(host_arch(), "x86_64")) return sbp_gnu_compile_x86_64;
    return sbp_gnu_compile_aarch64;
}

uptr sbp_gnu_program() {
    if (str_eq(host_arch(), "x86_64")) return sbp_gnu_program_x86_64;
    return sbp_gnu_program_aarch64;
}
